export const POST_SEARCH_BY_JURUSAN = 'POST_SEARCH_BY_JURUSAN'
export const POST_SEARCH_BY_JURUSAN_SUCCESS = 'POST_SEARCH_BY_JURUSAN_SUCCESS'
export const POST_SEARCH_BY_JURUSAN_FAILED = 'POST_SEARCH_BY_JURUSAN_FAILED'

export const POST_SEARCH_BY_JUDUL = 'POST_SEARCH_BY_JUDUL'
export const POST_SEARCH_BY_JUDUL_SUCCESS = 'POST_SEARCH_BY_JUDUL_SUCCESS'
export const POST_SEARCH_BY_JUDUL_FAILED = 'POST_SEARCH_BY_JUDUL_FAILED'

export const POST_SEARCH_BY_BORROW_DATE = 'POST_SEARCH_BY_BORROW_DATE'
export const POST_SEARCH_BY_BORROW_DATE_SUCCESS = 'POST_SEARCH_BY_BORROW_DATE_SUCCESS'
export const POST_SEARCH_BY_BORROW_DATE_FAILED = 'POST_SEARCH_BY_BORROW_DATE_FAILED'

export const POST_SEARCH_BY_BORROW_DATE_ADMIN = 'POST_SEARCH_BY_BORROW_DATE_ADMIN'
export const POST_SEARCH_BY_BORROW_DATE_ADMIN_SUCCESS = 'POST_SEARCH_BY_BORROW_DATE_ADMIN_SUCCESS'
export const POST_SEARCH_BY_BORROW_DATE_ADMIN_FAILED = 'POST_SEARCH_BY_BORROW_DATE_ADMIN_FAILED'

export const POST_SEARCH_BY_RETURN_DATE = 'POST_SEARCH_BY_RETURN_DATE'
export const POST_SEARCH_BY_RETURN_DATE_SUCCESS = 'POST_SEARCH_BY_RETURN_DATE_SUCCESS'
export const POST_SEARCH_BY_RETURN_DATE_FAILED = 'POST_SEARCH_BY_RETURN_DATE_FAILED'

export const POST_SEARCH_BY_RETURN_DATE_ADMIN = 'POST_SEARCH_BY_RETURN_DATE_ADMIN'
export const POST_SEARCH_BY_RETURN_DATE_ADMIN_SUCCESS = 'POST_SEARCH_BY_RETURN_DATE_ADMIN_SUCCESS'
export const POST_SEARCH_BY_RETURN_DATE_ADMIN_FAILED = 'POST_SEARCH_BY_RETURN_DATE_ADMIN_FAILED'