export const GET_SEARCH_BY_JURUSAN = 'GET_SEARCH_BY_JURUSAN'
export const GET_SEARCH_BY_JURUSAN_SUCCESS = 'GET_SEARCH_BY_JURUSAN_SUCCESS'
export const GET_SEARCH_BY_JURUSAN_FAILED = 'GET_SEARCH_BY_JURUSAN_FAILED'

export const GET_SEARCH_BY_JUDUL = 'GET_SEARCH_BY_JUDUL'
export const GET_SEARCH_BY_JUDUL_SUCCESS = 'GET_SEARCH_BY_JUDUL_SUCCESS'
export const GET_SEARCH_BY_JUDUL_FAILED = 'GET_SEARCH_BY_JUDUL_FAILED'
export const GET_SEARCH_BY_JUDUL_RESET= 'GET_SEARCH_BY_JUDUL_RESET'

export const GET_SEARCH_BY_BORROW_DATE = 'GET_SEARCH_BY_BORROW_DATE'
export const GET_SEARCH_BY_BORROW_DATE_SUCCESS = 'GET_SEARCH_BY_BORROW_DATE_SUCCESS'
export const GET_SEARCH_BY_BORROW_DATE_FAILED = 'GET_SEARCH_BY_BORROW_DATE_FAILED'

export const GET_SEARCH_BY_BORROW_DATE_ADMIN = 'GET_SEARCH_BY_BORROW_DATE_ADMIN'
export const GET_SEARCH_BY_BORROW_DATE_ADMIN_SUCCESS = 'GET_SEARCH_BY_BORROW_DATE_ADMIN_SUCCESS'
export const GET_SEARCH_BY_BORROW_DATE_ADMIN_FAILED = 'GET_SEARCH_BY_BORROW_DATE_ADMIN_FAILED'
export const RESET_MESSAGE = "RESET_MESSAGE"

export const GET_SEARCH_BY_RETURN_DATE = 'GET_SEARCH_BY_RETURN_DATE'
export const GET_SEARCH_BY_RETURN_DATE_SUCCESS = 'GET_SEARCH_BY_RETURN_DATE_SUCCESS'
export const GET_SEARCH_BY_RETURN_DATE_FAILED = 'GET_SEARCH_BY_RETURN_DATE_FAILED'

export const GET_SEARCH_BY_RETURN_DATE_ADMIN = 'GET_SEARCH_BY_RETURN_DATE_ADMIN'
export const GET_SEARCH_BY_RETURN_DATE_ADMIN_SUCCESS = 'GET_SEARCH_BY_RETURN_DATE_ADMIN_SUCCESS'
export const GET_SEARCH_BY_RETURN_DATE_ADMIN_FAILED = 'GET_SEARCH_BY_RETURN_DATE_ADMIN_FAILED'

