export const GET_BORROW_ADMIN = 'GET_BORROW_ADMIN'
export const GET_BORROW_ADMIN_SUCCESS = 'GET_BORROW_ADMIN_SUCCESS'
export const GET_BORROW_ADMIN_FAILED = 'GET_BORROW_ADMIN_FAILED'

export const GET_BORROW = 'GET_BORROW'
export const GET_BORROW_SUCCESS = 'GET_BORROW_SUCCESS'
export const GET_BORROW_FAILED = 'GET_BORROW_FAILED'

export const POST_BORROW = 'POST_BORROW'
export const POST_BORROW_SUCCESS = 'POST_BORROW_SUCCESS'
export const POST_BORROW_FAILED = 'POST_BORROW_FAILED'

export const POST_ACCEPT_BORROW = 'POST_ACCEPT_BORROW'
export const POST_ACCEPT_BORROW_SUCCESS = 'POST_ACCEPT_BORROW_SUCCESS'
export const POST_ACCEPT_BORROW_FAILED = 'POST_ACCEPT_BORROW_FAILED'

export const POST_DENIED_BORROW = 'POST_DENIED_BORROW'
export const POST_DENIED_BORROW_SUCCESS = 'POST_DENIED_BORROW_SUCCESS'
export const POST_DENIED_BORROW_FAILED = 'POST_DENIED_BORROW_FAILED'

export const DELETE_BORROW = 'DELETE_BORROW'
export const DELETE_BORROW_SUCCESS = 'DELETE_BORROW_SUCCESS'

export const DOWNLOAD_BORROW = 'DOWNLOAD_BORROW'
export const DOWNLOAD_BORROW_SUCCESS = 'DOWNLOAD_BORROW_SUCCESS'
export const DOWNLOAD_BORROW_FAILED = 'DOWNLOAD_BORROW_FAILED'

export const CLEAR_BORROW_MESSAGE = 'CLEAR_BORROW_MESSAGE'
