export const GET_DASHBOARD = 'GET_DASHBOARD'
export const GET_DASHBOARD_SUCCESS = 'GET_DASHBOARD_SUCCESS'
export const GET_DASHBOARD_FAILED = 'GET_DASHBOARD_FAILED'

export const GET_WHATSAPP= 'GET_WHATSAPP'
export const GET_WHATSAPP_SUCCESS= 'GET_WHATSAPP_SUCCESS'