export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const LOGOUT = 'LOGOUT'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const REGISTER = 'REGISTER'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILED = 'REGISTER_FAILED'

export const AUTH_INFO = 'AUTH_INFO'
export const AUTH_INFO_SUCCESS = 'AUTH_INFO_SUCCESS'
export const AUTH_INFO_FAILED = 'AUTH_INFO_FAILED'