export const GET_INVENTORY = 'GET_INVENTORY' 
export const GET_INVENTORY_SUCCESS = 'GET_INVENTORY_SUCCESS' 
export const GET_INVENTORY_FAILED = 'GET_INVENTORY_FAILED'

export const POST_INVENTORY = 'POST_INVENTORY'
export const POST_INVENTORY_SUCCESS = 'POST_INVENTORY_SUCCESS'
export const POST_INVENTORY_FAILED = 'POST_INVENTORY_FAILED'

export const EDIT_INVENTORY = 'EDIT_INVENTORY'
export const EDIT_INVENTORY_SUCCESS = 'EDIT_INVENTORY_SUCCESS'
export const EDIT_INVENTORY_FAILED = 'EDIT_INVENTORY_FAILED'

export const DELETE_INVENTORY = 'DELETE_INVENTORY'
export const DELETE_INVENTORY_SUCCESS = 'DELETE_INVENTORY_SUCCESS'
export const DELETE_INVENTORY_FAILED = 'DELETE_INVENTORY_FAILED'

export const CLEAR_INVENTORY_MESSAGE = 'CLEAR_INVENTORY_MESSAGE'