export const GET_INVENTORY = 'GET_INVENTORY' 
export const GET_INVENTORY_SUCCESS = 'GET_INVENTORY_SUCCESS' 
export const GET_INVENTORY_FAILED = 'GET_INVENTORY_FAILED'

export const POST_INVENTORY = 'POST_INVENTORY'
export const POST_INVENTORY_SUCCESS = 'POST_INVENTORY_SUCCESS'
export const POST_INVENTORY_FAILED = 'POST_INVENTORY_FAILED'