export const GET_JURUSAN = 'GET_JURUSAN'
export const GET_JURUSAN_SUCCESS = 'GET_JURUSAN_SUCCESS'
export const GET_JURUSAN_FAILED = 'GET_JURUSAN_FAILED'

export const POST_JURUSAN = 'POST_JURUSAN'
export const POST_JURUSAN_SUCCESS = 'POST_JURUSAN_SUCCESS'
export const POST_JURUSAN_FAILED = 'POST_JURUSAN_FAILED'

export const PATCH_JURUSAN = 'PATCH_JURUSAN'
export const PATCH_JURUSAN_SUCCESS = 'PATCH_JURUSAN_SUCCESS'
export const PATCH_JURUSAN_FAILED = 'PATCH_JURUSAN_FAILED'

export const DELETE_JURUSAN = 'DELETE_JURUSAN'
export const DELETE_JURUSAN_SUCCESS = 'DELETE_JURUSAN_SUCCESS'
// export const DELETE_JURUSAN_FAILED = 'DELETE_JURUSAN_FAILED'

export const CLEAR_JURUSAN_MESSAGES = 'CLEAR_JURUSAN_MESSAGES'