export const GET_ACCOUNT = 'GET_ACCOUNT'
export const GET_ACCOUNT_SUCCESS = 'GET_ACCOUNT_SUCCESS'
export const GET_ACCOUNT_FAILED = 'GET_ACCOUNT_FAILED'

export const DELETE_ACCOUNT = 'DELETE_ACCOUNT'
export const DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS'

export const EDIT_ACCOUNT = 'EDIT_ACCOUNT'
export const EDIT_ACCOUNT_SUCCESS = 'EDIT_ACCOUNT_SUCCESS'
export const EDIT_ACCOUNT_FAILED = 'EDIT_ACCOUNT_FAILED'

export const POST_ACCOUNT_ADMIN ='POST_ACCOUNT_ADMIN'
export const POST_ACCOUNT_ADMIN_SUCCESS = 'POST_ACCOUNT_ADMIN_SUCCESS'
export const POST_ACCOUNT_ADMIN_FAILED = 'POST_ACCOUNT_ADMIN_FAILED'

export const POST_ACCOUNT_SUPER ='POST_ACCOUNT_SUPER'
export const POST_ACCOUNT_SUPER_SUCCESS = 'POST_ACCOUNT_SUPER_SUCCESS'
export const POST_ACCOUNT_SUPER_FAILED = 'POST_ACCOUNT_SUPER_FAILED'

export const CLEAR_ACCOUNT_MESSAGE = 'CLEAR_ACCOUNT_MESSAGE'

export const POST_BLOCK ='POST_BLOCK'
export const POST_BLOCK_SUCCESS ='POST_BLOCK_SUCCESS'
export const POST_BLOCK_FAILED = 'POST_BLOCK_FAILED'

export const POST_UNBLOCK ='POST_UNBLOCK'
export const POST_UNBLOCK_SUCCESS ='POST_UNBLOCK_SUCCESS'
export const POST_UNBLOCK_FAILED ='POST_UNBLOCK_FAILED'