export const GENERATE_BARCODE = 'GENERATE_BARCODE'
export const GENERATE_BARCODE_SUCCESS = 'GENERATE_BARCODE_SUCCESS'
export const GENERATE_BARCODE_FAILED = 'GENERATE_BARCODE_FAILED'

export const SCAN_BARCODE = 'SCAN_BARCODE'
export const SCAN_BARCODE_SUCCESS = 'SCAN_BARCODE_SUCCESS'
export const SCAN_BARCODE_FAILED = 'SCAN_BARCODE_FAILED'

export const GET_PRESENT = 'GET_PRESENT'
export const GET_PRESENT_SUCCESS = 'GET_PRESENT_SUCCESS'
export const GET_PRESENT_FAILED = 'GET_PRESENT_FAILED'

export const DOWNLOAD_PRESENTS = 'DOWNLOAD_PRESENTS'
export const DOWNLOAD_PRESENTS_SUCCESS = 'DOWNLOAD_PRESENTS_SUCCESS'
export const DOWNLOAD_PRESENTS_FAILED = 'DOWNLOAD_PRESENTS_FAILED'