export const PUT_PROFILE = 'PUT_PROFILE'
export const PUT_PROFILE_SUCCESS = 'PUT_PROFILE_SUCCESS'
export const PUT_PROFILE_FAILED = 'PUT_PROFILE_FAILED'

export const CLEAR_EDIT_PROFILE_MESSAGE = 'CLEAR_EDIT_PROFILE_MESSAGE';