export const GET_RETURN_ADMIN = 'GET_RETURN_ADMIN'
export const GET_RETURN_ADMIN_SUCCESS = 'GET_RETURN_ADMIN_SUCCESS'
export const GET_RETURN_ADMIN_FAILED = 'GET_RETURN_ADMIN_FAILED'

export const GET_RETURN = 'GET_RETURN'
export const GET_RETURN_SUCCESS = 'GET_RETURN_SUCCESS'
export const GET_RETURN_FAILED = 'GET_RETURN_FAILED'

export const POST_ACCEPT_RETURN = 'POST_ACCEPT_RETURN'
export const POST_ACCEPT_RETURN_SUCCESS = 'POST_ACCEPT_RETURN_SUCCESS'
export const POST_ACCEPT_RETURN_FAILED = 'POST_ACCEPT_RETURN_FAILED'

export const POST_RESET_RETURN = 'POST_RESET_RETURN'
export const POST_RESET_RETURN_SUCCESS = 'POST_RESET_RETURN_SUCCESS'
export const POST_RESET_RETURN_FAILED = 'POST_RESET_RETURN_FAILED'

export const DOWNLOAD = 'DOWNLOAD'
export const DOWNLOAD_SUCCESS = 'DOWNLOAD_SUCCESS'
export const DOWNLOAD_FAILED = 'DOWNLOAD_FAILED'